name: Q6
run-name: Maxime Galmant Q6
on: [push]
permissions:
 contents: write
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Git user
        run: |
          git config --global user.name RyuuAz
          git config --global user.email max.galmant@gmail.com
      
      - name: Copie Q6.java
        run: |
          echo "Maxime Galmant" > Q6_archive_java.txt
          cat ./Q6.java >> Q6_archive_java.txt
          echo "$(date + "%d-%m-%Y-%H%M%S")" >> Q6_archive_java.txt
          wc -l ./Q6.java >> Q6_archive_java.txt
          wc -m ./Q6.java >> Q6_archive_java.txt
          diff Q6_archive_java.txt ./Q6_archive_java.txt >> Q6_diff√©rences.txt
      
      - name: Commit and push the new file
        run: |
          git add Q6_archive_java.txt
          git commit -m "test push de Q6_archive_java.txt"
          git push
